Added type-specimen | Improved type-specimen
I can't fucking commit via cmd anymore

D:\School\School\My Project>git push origin main
To https://github.com/vanhong-luy/my_projects.git
 ! [rejected]          main -> main (fetch first)
error: failed to push some refs to 'https://github.com/vanhong-luy/my_projects.git'
hint: Updates were rejected because the remote contains work that you do not
hint: have locally. This is usually caused by another repository pushing to
hint: the same ref. If you want to integrate the remote changes, use
hint: 'git pull' before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

gg